-- 01_create_tables.sql (PostgreSQL)
CREATE TABLE cliente (
  id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(80) NOT NULL,
  email VARCHAR(120) UNIQUE NOT NULL,
  telefono VARCHAR(20),
  direccion TEXT
);

CREATE TABLE producto (
  id_producto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(12,2) NOT NULL CHECK (precio > 0),
  stock INT NOT NULL CHECK (stock >= 0)
);

CREATE TABLE proveedor (
  id_proveedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  direccion TEXT,
  telefono VARCHAR(20),
  email VARCHAR(120) UNIQUE
);

-- Relación N:M entre producto y proveedor
CREATE TABLE producto_proveedor (
  id_producto INT NOT NULL,
  id_proveedor INT NOT NULL,
  precio_compra NUMERIC(12,2) CHECK (precio_compra > 0),
  PRIMARY KEY (id_producto, id_proveedor),
  FOREIGN KEY (id_producto) REFERENCES producto(id_producto),
  FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor)
);

CREATE TABLE pedido (
  id_pedido INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL DEFAULT CURRENT_DATE,
  estado VARCHAR(20) NOT NULL CHECK (estado IN ('pendiente','pagado','cancelado','enviado')),
  id_cliente INT NOT NULL REFERENCES cliente(id_cliente),
  total NUMERIC(12,2) NOT NULL CHECK (total >= 0)
);

CREATE TABLE detalle_pedido (
  id_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido INT NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
  id_producto INT NOT NULL REFERENCES producto(id_producto),
  cantidad INT NOT NULL CHECK (cantidad > 0),
  precio_unitario NUMERIC(12,2) NOT NULL CHECK (precio_unitario > 0)
);

CREATE TABLE pago (
  id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido INT NOT NULL REFERENCES pedido(id_pedido) ON DELETE CASCADE,
  metodo VARCHAR(30) NOT NULL CHECK (metodo IN ('efectivo','tarjeta','transferencia')),
  monto NUMERIC(12,2) NOT NULL CHECK (monto > 0),
  fecha_pago TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX idx_pedido_cliente ON pedido(id_cliente);
CREATE INDEX idx_detalle_pedido_producto ON detalle_pedido(id_producto);
